[project]
name = "bt-speaker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bech32>=1.2.0",
    "fastapi>=0.136.0",
    "httpx>=0.28.1",
    "ishelly",
    "pygame>=2.6.1",
    "uvicorn>=0.45.0",
]

[tool.uv.sources]
ishelly = { path = "../ishelly", editable = true }
